title: "Rhythm: Sass files for vertical rhythm using modular scales"

compress_html:
  clippings: all
  endings: all
  startings: [html, head, body]

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
